name = "lol-stats"
main = "src/index.js"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_OWNER = "closur3"
GITHUB_REPOSITORY = "lol-stats-archive"

[[kv_namespaces]]
binding = "lol-stats-kv"
id = "132afd73154a4972be43f18fdf1dc5d5"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[dev]
ip = "0.0.0.0"
port = 8787
